### PR TITLE
add parameter MAGENTO_ELASTICSEARCH_USE_HTTPS for working with Opensearch managed service

### PR DESCRIPTION
**Pull request by allamand**
Signed-off-by: Sébastien Allamand <sebastien@allamand.com>

**Description of the change**

I added a new configuration parameter for connecting to ElasticSearch: MAGENTO_ELASTICSEARCH_USES_HTTPS.
default is no, which behave like before.
If value ie yes, then it add the prefix 'https://' when making the request to elasticsearch.

**Benefits**

Without this change, it was not possible to connect Magento on AWS managed Opensearch Service which needs https.

**Possible drawbacks**

**Applicable issues**

**Additional information**

### CODE REVIEW

**Review by alemorcuq — CHANGES_REQUESTED** [review]
Thanks! Could you rename it to `MAGENTO_ELASTICSEARCH_USE_HTTPS`, as you did in the README?

**Comment by allamand** [comment]
@alemorcuq I just make the change.

**Review by alemorcuq — APPROVED** [review]
Thanks!

**Comment by allamand** [comment]
what is your process for releasing ? when this can be merge ?

**Comment by alemorcuq** [comment]
> what is your process for releasing ? when this can be merge ?

I'm merging it now, and then we will have to wait for our internal pipeline to release a new tag of the container.

**Comment by allamand** [comment]
Awesome, thanks

**Pull request merged**
